//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class feedbacks
    {
        public int feedback_id { get; set; }
        public Nullable<System.DateTime> initiated { get; set; }
        public Nullable<System.DateTime> received { get; set; }
        public Nullable<int> project_id { get; set; }
        public string Id { get; set; }
    }
}
