//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projects
    {
        public int project_id { get; set; }
        public string acronym { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string status { get; set; }
        public Nullable<int> department_id { get; set; }
    
        public virtual departments departments { get; set; }
    }
}
